apiVersion: v2
publisher: Wellness Tech Group
name: smartclide-deployment-extension
version: 0.0.0
type: Che Extension
displayName: SmartCLIDE Deployment Extension
title: SmartCLIDE Deployment Extension
description: Che Extension deploy an image Dockerfile of a Docker container in a Kubernetes cluster.
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
repository: https://github.com/eclipse-researchlabs/smartclide-deployment-extension
firstPublicationDate: '2022-06-16'
category: Other
